# Generated by Django 4.2.5 on 2023-09-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_dish_created_at_alter_dish_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='menu',
            field=models.ManyToManyField(to='restaurants.menu'),
        ),
    ]
