# Generated by Django 4.2.5 on 2023-09-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_dish_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='menu',
            field=models.ManyToManyField(related_name='menu_item', to='restaurants.menu'),
        ),
    ]
