# Generated by Django 4.2.5 on 2023-09-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_table_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='table',
            name='is_available',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
