# Generated by Django 4.2.5 on 2023-09-10 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_dish_menu'),
        ('orders', '0003_alter_order_is_completed_alter_table_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(blank=True, related_name='order_item', through='orders.OrderItem', to='restaurants.dish'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.table'),
        ),
    ]
